enabled: false

global:
  defaults:
    availability: 99.9
    latency: 99
    latencyThreshold: 100
    rate5xx: 0.05
    rate4xx: 5

namespace: observability

prependReleaseNameToDeployment: false

grafanaURL: ""

istioMetrics:
  enabled: true

nginxIngressMetrics:
  enabled: false
services: []
# - deploymentName: "sample"

#   slo: {}
#     # availability: 99.9
#     # latency: 99
#     # latencyThreshold: 100
 
#   errorRate: {}
#     # rate4xx: 5
#     # rate5xx: 0.05
  
#   ingressName: "smaple-ingress"
#   serviceName: "sample-service"