{{- if (lookup "networking.k8s.io/v1" "IngressClass" "nginx")  }}
{{- if .Values.nopo11y_health_check.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nopo11y-health-check-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/add-base-url : "true"
spec:
  ingressClassName: nginx
  rules:
  {{- if hasKey .Values.nopo11y_health_check.ingress "host" }}
  - host: {{ .Values.nopo11y_health_check.ingress.host }}
    http:
  {{- else }}
  - http:
  {{- end }}
      paths:
      - backend:
          service:
            name: kuberhealthy
            port:
              number: 80
        path: /nopo11y-health-check
        pathType: Prefix
{{- end }}
{{- end }}