{{- if .Values.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "app.label" . }}-default-alert-rules
  labels:
    release: {{ .Values.prometheusReleaseLabel }}
spec:
  groups:
  - name: {{ include "app.label" . }}-default-alert-rules
    rules:
    {{- if .Values.istioMetrics.enabled }}
    - alert: {{ include "app.label" . }}High5xxErrorRate
      expr: sum(rate(istio_requests_total{app="{{ include "app.label" . }}", destination_app=~"{{ include "app.label" . }}", response_code=~"5.."}[5m])) by (instance) / sum(rate(istio_requests_total{app="{{ include "app.label" . }}", destination_app=~"{{ include "app.label" . }}"}[5m])) by (instance) * 100 > {{ .Values.errorRate5xx }}
      annotations:
        description: {{ include "app.label" . }} service is experiencing high 5xx errors rate from last 5 minutes.
        summary: {{ include "app.label" . }} service is experiencing high 5xx error rate.
        {{- if .Values.grafanaURL }}
        dashboard: {{ .Values.grafanaURL }}/d/{{ include "dashboard-uid" .}}
        {{- end }}
      labels:
            severity: critical
    - alert: {{ include "app.label" . }}High4xxErrorRate
      expr: sum(rate(istio_requests_total{app="{{ include "app.label" . }}", destination_app=~"{{ include "app.label" . }}", response_code=~"4.."}[5m])) by (instance) / sum(rate(istio_requests_total{app="{{ include "app.label" . }}", destination_app=~"{{ include "app.label" . }}"}[5m])) by (instance) * 100 > {{ .Values.errorRate4xx }}
      for: 5m
      annotations:
        {{- if .Values.grafanaURL }}
        dashboard: {{ .Values.grafanaURL }}/d/{{ include "dashboard-uid" .}}
        {{- end }}
        description: {{ include "app.label" . }} service is experiencing high 4xx errors rate from last 5 minutes.
        summary: {{ include "app.label" . }} service is experiencing high 4xx error rate.
      labels:
            severity: warning
    {{- end }}
    {{- if .Values.nginxIngressMetrics.enabled }}
    - alert: {{ include "app.label" . }}IngressHigh5xxErrorRate
      expr: sum(rate(nginx_ingress_controller_requests{ingress=~"{{ .Values.nginxIngressMetrics.ingressName }}",status=~"5.."}[5m])) / sum(rate(nginx_ingress_controller_requests{ingress=~"{{ .Values.nginxIngressMetrics.ingressName }}"}[5m])) * 100 > {{ .Values.errorRate5xx }}
      annotations:
        description: {{ include "app.label" . }} service is experiencing high 5xx errors rate from last 5 minutes.
        summary: {{ include "app.label" . }} is experiencing high 5xx error rate.
        {{- if .Values.grafanaURL }}
        dashboard: {{ .Values.grafanaURL }}/d/{{ include "dashboard-uid" .}}
        {{- end }}
      labels:
            severity: critical
    - alert: {{ include "app.label" . }}IngressHigh4xxErrorRate
      expr: sum(rate(nginx_ingress_controller_requests{ingress=~"{{ .Values.nginxIngressMetrics.ingressName }}",status=~"4.."}[5m])) / sum(rate(nginx_ingress_controller_requests{ingress=~"{{ .Values.nginxIngressMetrics.ingressName }}"}[5m])) * 100 > {{ .Values.rrorRate4xx }}
      for: 10m
      annotations:
        description: {{ include "app.label" . }} service is experiencing high 4xx errors rate from last 5 minutes.
        summary: {{ include "app.label" . }} service is experiencing high 4xx error rate.
        {{- if .Values.grafanaURL }}
        dashboard: {{ .Values.grafanaURL }}/d/{{ include "dashboard-uid" .}}
        {{- end }}
      labels:
            severity: warning
    {{- end }}
{{- end }}