{{- $valid := list "DEBUG" "INFO" "WARNING" "ERROR" "CRITICAL" -}}
{{- if not (has .Values.prom2teams.loglevel $valid) -}}
{{- fail "Invalid log level"}}
{{- end -}}
{{- if and .Values.prom2teams.connector (hasKey .Values.prom2teams.connectors "Connector") -}}
{{- fail "Invalid configuration: prom2teams.connectors can't have a connector named Connector when prom2teams.connector is set"}}
{{- end -}}
{{- if and (not .Values.prom2teams.connector) (not .Values.prom2teams.connectors) -}}
{{- fail "Invalid configuration: At least one connector must be provided"}}
{{- end -}}
{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prom2teams-config
  namespace: {{ .Release.Namespace | quote }}
spec:
  refreshInterval: {{ .Values.externalSecrets.externalSecretsRefreshInterval }}
  secretStoreRef:
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
  target:
    name: prom2teams-config
    template:
      data:
        config.ini: |-
          [HTTP Server]
          Host: {{ .Values.prom2teams.host }}
          Port: {{ .Values.prom2teams.port }}
          [Microsoft Teams]
          {{- if .Values.prom2teams.connector }}
          Connector: "{{ "{{" }} .connector {{ "}}" }}" 
          {{- end }}
          {{- range $key, $val := .Values.prom2teams.connectors }}
          {{ $key }}: "{{ "{{" }} .{{ $key }}_connector {{ "}}" }}"
          {{- end }}
          [Group Alerts]
          Field: {{ .Values.prom2teams.group_alerts_by }}
          [Log]
          Level: {{ .Values.prom2teams.loglevel }}
          [Template]
          Path: {{ .Values.prom2teams.templatepath }}
  data:
  {{- if .Values.prom2teams.connector }}
  - secretKey: connector
    remoteRef:
      key: {{ .Values.prom2teams.connector }}
  {{- end }}
  {{- range $key, $val := .Values.prom2teams.connectors }}
  - secretKey: {{ $key }}_connector
    remoteRef:
      key: {{ $val }}
  {{- end }}
{{- end }}